### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by dgladkov** [notfier/blog#1]
Files/dirs that should not be committed

```
*.sqlite3
*.pyc
__pycache__/
```

Add them to .gitignore and remove them from repository

Example .gitignore for Python projects:

https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by dgladkov** [comment]
Same goes for `media/`

**Comment by notfier** [comment]
Thanks you a lot. I fixed it.
