### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by dgladkov** [notfier/blog#2]
Следующие тесткейсы не имеют смысла:

```
PostTest
TestTag
TestComments
```

В них по сути ты тестируешь то, что Django умеет создавать модели. Этот функционал уже протестирован в тесткейсах джанго и самому тестировать это не нужно:)

Что нужно тестировать:
1. Методы моделей (get_absolute_url не обязательно)
2. Менеджеры
3. Middleware/Context Processors
4. Views

**Comment by notfier** [comment]
Спасибо большое) Я учту Ваши замечания. Действительно глупость сделал
